### ISSUE TITLE
net = get_resnet   TypeError: __init__() takes at least 2 arguments (2 given) 

### ISSUE THREAD

**Issue by adong7639** [auroua/InsightFace_TF#30]
[TL] InputLayer  resnet_v1_50/input_layer: (?, 112, 112, 3)
[TL] Conv2d resnet_v1_50/conv1: shape:(3, 3, 3, 64) strides:(1, 1, 1, 1) pad:SAME act:identity
Traceback (most recent call last):
  File "train_nets.py", line 77, in <module>
    net = get_resnet(images, args.net_depth, type='ir', w_init=w_init_method, trainable=True, keep_rate=dropout_rate)
  File "/home/ai/InsightFace_TF/nets/L_Resnet_E_IR_fix_issue9.py", line 399, in get_resnet
    scope='resnet_v1_%d' % num_layers)
  File "/home/ai/InsightFace_TF/nets/L_Resnet_E_IR_fix_issue9.py", line 301, in resnet
    net = BatchNormLayer(net, act=tf.identity, name='bn0', is_train=True, trainable=trainable)
  File "/home/ai/InsightFace_TF/nets/L_Resnet_E_IR_fix_issue9.py", line 110, in __init__
    Layer.__init__(self, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorlayer/deprecation.py", line 24, in wrapper
    return f(*args, **kwargs)
TypeError: __init__() takes at least 2 arguments (2 given)

my version: 
tensorflow 1.4  tensorlayer 1.8.4

someone have same porblem ,  please give me some soutions, thanks

**Comment by adong7639** [comment]
I solve the problem like this: 
        #Layer.__init__(self, name=name)
        self.name = name
