### ISSUE TITLE
UnicodeEncodeError in mx2tfrecords.py

### ISSUE THREAD

**Issue by HsuTzuJen** [auroua/InsightFace_TF#7]
when I excute mx2tfrecords.py and it is exuted to "images, labels = sess.run(next_element)", Error occured:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py:560: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2927, in run_code
    self.showtraceback(running_compiled_code=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1833, in showtraceback
    self._showtraceback(etype, value, stb)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 558, in _showtraceback
    dh.parent_header, ident=topic)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\session.py", line 737, in send
    to_send = self.serialize(msg, ident)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\session.py", line 625, in serialize
    content = self.pack(content)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,

  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\jsonapi.py", line 43, in dumps
    s = s.encode('utf8')

UnicodeEncodeError: 'utf-8' codec can't encode character '\udca8' in position 2124: surrogates not allowed

**Comment by auroua** [comment]
I think this is caused by the `operate system`. I tested the code in `ubuntu 16.04`.

**Comment by HsuTzuJen** [comment]
Thank you!
I just found that it was caused by the wrong path of tfrecord .
